# Generated by Django 5.2.5 on 2025-08-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='custumer',
            new_name='customer',
        ),
    ]
